name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          cd project && npm install

      - name: Lint
        working-directory: project
        run: npm run lint

      - name: Build
        working-directory: project
        run: npm run build

      - name: Verify build output
        run: |
          if [ ! -d "project/dist" ]; then
            echo "Build failed: project/dist directory not found"
            exit 1
          fi
          echo "Build successful! Found project/dist directory"
          echo "Build size: $(du -sh project/dist/)"
          ls -la project/dist/

